project_id = "ctqbadyfhcoxhywrkorf"

[functions.newsletter-signup]
verify_jwt = false

[functions.send-newsletter]
verify_jwt = false

[functions.sync-constant-contact]
verify_jwt = false

[functions.exchange-cc-token]
verify_jwt = false
