project_id = "ctqbadyfhcoxhywrkorf"

[functions.newsletter-signup]
verify_jwt = false

[functions.send-newsletter]
verify_jwt = true

[functions.mailchimp-subscribe]
verify_jwt = false

[functions.sync-mailchimp]
verify_jwt = false

[functions.course-enroll]
verify_jwt = false

[functions.send-course-email]
verify_jwt = true

[functions.personalized-suggestions]
verify_jwt = false
